### ISSUE TITLE
libdnf-Warning - cannot move

### ISSUE THREAD

**Issue by glennswest** [rpm-software-management/microdnf#27] opened 2017-06-26 08:34 UTC
Doing a build on a container, and if I do multiple installs, seems to get issues on cache data:

[root@dev svcmaps]# ./buildbug.sh 
Sending build context to Docker daemon 80.38 kB
Step 1/50 : FROM registry.access.redhat.com/rhel7-atomic:latest
 ---> b2a215996d7a
Step 2/50 : RUN microdnf update
 ---> Using cache
 ---> 600ac3c5b869
Step 3/50 : RUN microdnf --enablerepo rhel-7-server-rpms install gzip
 ---> Using cache
 ---> 3db871c9de33
Step 4/50 : RUN microdnf --enablerepo rhel-7-server-rpms install zlib.x86_64
 ---> Running in b9488ba6fe15
Downloading metadata...

(microdnf:1): libdnf-WARNING **: Skipping refresh of rhel-7-server-rpms: cannot move /var/cache/yum/metadata/rhel-7-server-rpms/packages to /var/cache/yum/metadata/rhel-7-server-rpms.tmp/packages
Nothing to do.
 ---> 9b046032c9cd
Removing intermediate container b9488ba6fe15
Step 5/50 : RUN microdnf --enablerepo rhel-7-server-rpms  install bzip2-devel
 ---> Running in ba0c80a33132
Downloading metadata...

(microdnf:1): libdnf-WARNING **: Skipping refresh of rhel-7-server-rpms: cannot move /var/cache/yum/metadata/rhel-7-server-rpms/packages to /var/cache/yum/metadata/rhel-7-server-rpms.tmp/packages
error: No package matches 'bzip2-devel'
The command '/bin/sh -c microdnf --enablerepo rhel-7-server-rpms  install bzip2-devel' returned a non-zero code: 1
[root@dev svcmaps]# 

Dockerfile.bug is:FROM registry.access.redhat.com/rhel7-atomic:latest
RUN microdnf update
RUN microdnf --enablerepo rhel-7-server-rpms install gzip
RUN microdnf --enablerepo rhel-7-server-rpms install zlib.x86_64
RUN microdnf --enablerepo rhel-7-server-rpms  install bzip2-devel
RUN microdnf --enablerepo rhel-7-server-rpms  install zip
RUN microdnf --enablerepo rhel-7-server-rpms  install postgresql
RUN microdnf --enablerepo rhel-7-server-rpms  install postgresql-server
RUN microdnf --enablerepo rhel-7-server-rpms  install postgresql-libs
RUN microdnf --enablerepo rhel-7-server-rpms  install postgresql-contrib
RUN microdnf --enablerepo rhel-7-server-rpms  install postgresql-common
RUN microdnf --enablerepo rhel-7-server-rpms  install postgresql-devel
RUN microdnf --enablerepo rhel-7-server-rpms  install postgis
RUN microdnf --enablerepo rhel-7-server-rpms  install unzip
RUN microdnf --enablerepo rhel-7-server-rpms  install librsvg2
RUN microdnf --enablerepo rhel-7-server-rpms  install librsvg2-devel
RUN microdnf --enablerepo rhel-7-server-rpms  install gnome-python2-rsvg
RUN microdnf --enablerepo rhel-7-server-rpms  install pygobject2
RUN microdnf --enablerepo rhel-7-server-rpms  install pygobject2-devel
RUN microdnf --enablerepo rhel-7-server-rpms  install cairo
RUN microdnf --enablerepo rhel-7-server-rpms  install cairo-devel
RUN microdnf --enablerepo rhel-7-server-rpms  install cairomm-devel
RUN microdnf --enablerepo rhel-7-server-rpms  install libjpeg-turbo-devel

If I do a microdnf clean all in between it will work, but rather slow.

Anyone seen this:

This is being built on RHEL, and building using a rhel-atomic-base image.

**Comment by jnach** [comment] 2019-05-23 14:48
Confirming, looking for root cause now.

**Comment by jrohel** [comment] 2019-12-06 19:57
The issue was fixed in libdnf (library used by microdnf).
Related fixes:
PR https://github.com/rpm-software-management/libdnf/pull/787
PR https://github.com/rpm-software-management/libdnf/pull/789

**Closed by jrohel** 2019-12-06 19:57 UTC
