### ISSUE TITLE
microdnf nothing provides error

### ISSUE THREAD

**Issue by huakim** [rpm-software-management/microdnf#135] opened 2023-08-06 11:11 UTC
When i tried to install gnome-keyring with microdnf, the following error is raised:
Problem: conflicting requests
nothing provides /usr/libexec/gcr-ssh-askpass needed by gnome-keyring-42.1-3.fc38.x86_64

But, when i ran microdnf repoquery --whatprovides /usr/libexec/gcr-ssh-askpass, then printed:
gcr3-0:3.41.1-5.fc38.i686
gcr3-0:3.41.1-5.fc38.x86_64

But with dnf installing gnome-keyring is working
It seems, that, during install, dnf checks provides in file list, but microdnf is not

**Comment by kontura** [comment] 2023-08-07 06:45
Hello, it seems your `microdnf` is provided by `dnf5`. You can verify by running: `microdnf --version`.

You are correct `dnf5` by default doesn't load/download filelists. The `gnome-keyring` is one of the few remaining problematic packages, for more details see here: https://bugzilla.redhat.com/show_bug.cgi?id=2180842.

Until this is fixed you can workaround it by running your microdnf install command with: `--setopt=optional_metadata_types=filelists`.

**Comment by j-mracek** [comment] 2023-08-07 06:47
I created a bug for correct component - https://bugzilla.redhat.com/show_bug.cgi?id=2229623

**Comment by j-mracek** [comment] 2023-08-07 06:48
I am closing the bug because the issue is in another component. I would like to move the conversation to https://bugzilla.redhat.com/show_bug.cgi?id=2229623.

**Closed** 2023-08-07 06:49 UTC
