### ISSUE TITLE
--setopt=varsdir=? not working

### ISSUE THREAD

**Issue by jamjon3** [rpm-software-management/microdnf#122] opened 2022-04-08 15:59 UTC
I was originally expecting this to work like dnf where I put a variable in the /etc/dnf/vars directory but the 'vars' directory didn't exist. I'm running this in a UBI container.

I'm not picky if there is some other 'default' directory for vars with microdnf where I can put in a variable. I tried to simply create that /etc/dnf/vars directory in a container and create that file with the variable I was looking to set but it doesn't seem to be read if I append 

--setopt=varsdir=/etc/dnf/vars (or /etc/dnf if 'vars' is implied)

It's unclear what I need to do here to set a variable and have microdnf read it from a /etc/yum.repos.d repo file.

I'm getting stuff like this

(microdnf:10): librepo-WARNING **: 15:32:45.762: Error resolving real path of

Inside the container, I've pointed the usual ubi repos to my nexus artifactory and I'm passing in the domain name as the variable

microdnf --disableplugin=subscription-manager --setopt=varsdir=/etc/dnf install -y nodej
microdnf --disableplugin=subscription-manager --setopt=varsdir=/etc/dnf/vars install -y nodej

**Comment by jamjon3** [comment] 2022-04-08 16:12
Tried this as well in the container

ENV DNF_VAR_nexussrc="https://${ARTIFACTORY_HOST}"

Note: The container is using this variable to pull the container and later in the Dockerfile

ARG UBI_TYPE=ubi8
ARG JDK_VER=11
ARG ARTIFACTORY_HOST
FROM ${ARTIFACTORY_HOST}:5444/${UBI_TYPE}/openjdk-${JDK_VER}:latest

ARG UBI_TYPE=ubi8
ARG RHEL_TYPE=el8
ARG MAVEN_VER=3.8.1
ARG ARTIFACTORY_HOST

**Comment by jrohel** [comment] 2022-04-19 11:27
The problem is not in microdnf. I'm preparing a PR for libdnf, which will apply variable substitution earlier and to all repository configuration options. https://github.com/rpm-software-management/libdnf/pull/1497

**Comment by jrohel** [comment] 2022-05-27 14:37
The issue was resolved. The fix was merged into libdnf. New version of libdnf was released.

**Closed by jrohel** 2022-05-27 14:37 UTC
